services:
  mysite:
    build: .
    environment:
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
      - ALLOWED_HOSTS=web.ricepotato.dev
    restart: unless-stopped

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysite
