# Generated by Django 5.2.1 on 2025-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='links', to='linker.tag'),
        ),
        migrations.DeleteModel(
            name='LinkTag',
        ),
    ]
