# Generated by Django 5.2.1 on 2025-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_tag_alter_link_options_link_tags_delete_linktag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
